# Generated by Django 3.2.5 on 2021-07-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_aid_py', '0002_auto_20210707_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
