# Generated by Django 3.2.5 on 2021-07-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_aid_py', '0003_auto_20210707_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratemodel',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
